"use client";

// src/components/content/table-of-contents.tsx
// Auto-generated table of contents from markdown headings (h2 and h3)
// Client component with IntersectionObserver for active heading tracking
// NOTE: Heading IDs are generated by mdx-components.tsx heading elements
//       This component extracts headings from raw markdown and generates matching IDs
//       The mdx-components.tsx headings (modified in Plan 03) add id attributes to rendered headings

import { useEffect, useState } from "react";
import Link from "next/link";

interface TableOfContentsProps {
  content: string;  // Raw markdown content string
}

interface Heading {
  id: string;
  text: string;
  level: number;
}

// Generate heading ID from text (must match mdx-components.tsx ID generation)
function generateHeadingId(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

// Extract headings from raw markdown content
function extractHeadings(content: string): Heading[] {
  const headingRegex = /^(#{2,3})\s+(.+)$/gm;
  const headings: Heading[] = [];
  let match;

  while ((match = headingRegex.exec(content)) !== null) {
    const level = match[1].length;
    const text = match[2].trim();
    const id = generateHeadingId(text);
    headings.push({ id, text, level });
  }

  return headings;
}

export function TableOfContents({ content }: TableOfContentsProps) {
  const [activeId, setActiveId] = useState<string>("");
  const headings = extractHeadings(content);

  // Return null if no headings found
  if (headings.length === 0) {
    return null;
  }

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        });
      },
      {
        rootMargin: '-100px 0px -66%',
      }
    );

    // Observe all heading elements
    headings.forEach((heading) => {
      const element = document.getElementById(heading.id);
      if (element) {
        observer.observe(element);
      }
    });

    return () => {
      observer.disconnect();
    };
  }, [headings]);

  return (
    <nav className="p-6 bg-muted/30 rounded-lg border border-border mb-12">
      <h2 className="text-lg font-semibold mb-4">Table of Contents</h2>
      <ul className="space-y-2">
        {headings.map((heading) => {
          const isActive = activeId === heading.id;
          const isH3 = heading.level === 3;

          return (
            <li key={heading.id} className={isH3 ? "ml-4" : ""}>
              <Link
                href={`#${heading.id}`}
                className={`text-sm hover:text-primary transition-colors block ${
                  isActive
                    ? "text-primary font-medium"
                    : "text-muted-foreground"
                }`}
              >
                {heading.text}
              </Link>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
